{{- $fullName := include "stoatchat.fullname" . -}}
{{- if .Values.global.subcharts.mongodb.enabled }}
{{- if not .Values.mongodb.auth.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $fullName }}-mongodb"
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "stoatchat.labels" . | nindent 4 }}
type: Opaque
stringData:
  mongodb-root-password: {{ include "stoatchat.deriveSecret" (dict "root" . "id" "mongodb" "length" 32) | quote }}
{{- end }}
{{- end }}

{{- if .Values.global.subcharts.redis.enabled }}
{{- if not .Values.redis.auth.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $fullName }}-redis"
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "stoatchat.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: {{ include "stoatchat.deriveSecret" (dict "root" . "id" "redis" "length" 32) | quote }}
{{- end }}
{{- end }}

{{- if .Values.global.subcharts.rabbitmq.enabled }}
{{- if not .Values.rabbitmq.auth.existingPasswordSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $fullName }}-rabbitmq"
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "stoatchat.labels" . | nindent 4 }}
type: Opaque
stringData:
  rabbitmq-password: {{ include "stoatchat.deriveSecret" (dict "root" . "id" "rabbitmq" "length" 32) | quote }}
{{- end }}
{{- end }}

{{- if .Values.global.subcharts.minio.enabled }}
{{- if not .Values.minio.auth.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $fullName }}-minio"
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "stoatchat.labels" . | nindent 4 }}
type: Opaque
stringData:
  root-user: {{ include "stoatchat.deriveSecret" (dict "root" . "id" "minio-user" "length" 12) | quote }}
  root-password: {{ include "stoatchat.deriveSecret" (dict "root" . "id" "minio-pass" "length" 32) | quote }}
{{- end }}
{{- end }}
