{{- $fullName := include "stoatchat.fullname" . -}}
{{- if and .Values.global.secret.vapid_key .Values.global.secret.vapid_public_key }}
{{- $existingSecret := lookup "v1" "Secret" .Values.global.namespace (printf "%s-vapid" $fullName) -}}
{{- if not $existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $fullName }}-vapid"
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-9"
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/resource-policy": keep
  labels:
    {{- include "stoatchat.labels" . | nindent 4 }}
type: Opaque
stringData:
  private_key: {{ .Values.global.secret.vapid_key | quote }}
  public_key: {{ .Values.global.secret.vapid_public_key | quote }}
{{- end }}
{{- end }}

