{{- $root := . -}}
{{- $fullName := include "stoatchat.fullname" . -}}
{{- range $instance := .Values.global.livekit.servers }}
{{- if $instance.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-livekit-{{ $instance.name }}
  namespace: {{ $root.Values.global.namespace }}
  labels:
    {{- include "stoatchat.labels" $root | nindent 4 }}
    stoat-app: {{ $fullName }}-livekit-{{ $instance.name }}
spec:
  type: {{ $root.Values.livekit.service.type }}
  ports:
    - name: http
      targetPort: http
      protocol: TCP
      port: {{ $instance.http_port | default 7880 }}
    - name: rtc-tcp
      targetPort: rtc-tcp
      protocol: TCP
      port: {{ $instance.rtc_tcp_port | default 7881 }}
    - name: rtc-udp
      targetPort: rtc-udp
      protocol: UDP
      port: {{ $instance.rtc_udp_port | default 7882 }}
    - name: turn-udp
      targetPort: turn-udp
      protocol: UDP
      port: {{ $instance.turn.udp_port | default 3478 }}
    {{- if gt ($instance.turn.tls_port | default 0) 0 }}
    - name: turn-tls
      targetPort: turn-tls
      protocol: TCP
      port: {{ $instance.turn.tls_port }}
    {{- end }}
  selector:
    {{- include "stoatchat.selectorLabels" $root | nindent 4 }}
    stoat-app: {{ $fullName }}-livekit-{{ $instance.name }}
{{- end }}
{{- end }}
