{{- $fullName := include "stoatchat.fullname" . -}}
{{- $s3Endpoint := .Values.global.subcharts.minio.connection_url | default (printf "http://%s-minio:9000" $fullName) -}}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $fullName }}-create-buckets-{{ now | date "20060102150405" }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "stoatchat.labels" . | nindent 4 }}
    stoat-app: {{ $fullName }}-create-buckets
spec:

  template:
    metadata:
      {{- with .Values.web.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        stoat-app: {{ $fullName }}-create-buckets
        {{- include "stoatchat.labels" . | nindent 8 }}
        {{- with .Values.web.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: Never
      containers:
        - name: create-buckets
          image: docker.io/minio/minio
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
          args:
            - |
              echo "Using S3 endpoint: ${S3_ENDPOINT}"
              while ! (/usr/bin/mc alias set s3 "${S3_ENDPOINT}" "${S3_ACCESS_KEY}" "${S3_SECRET_KEY}" --api S3v4 >/dev/null 2>&1 && /usr/bin/mc ls s3 >/dev/null 2>&1); do
                echo 'Waiting S3 endpoint...' && sleep 2
              done
              /usr/bin/mc mb --ignore-existing "s3/${S3_BUCKET}"
              exit 0
          env:
            - name: S3_ENDPOINT
              value: {{ $s3Endpoint | quote }}
            - name: S3_BUCKET
              value: "revolt-uploads"
            - name: S3_ACCESS_KEY
              value: {{ .Values.global.subcharts.minio.access_key_id | default .Values.minio.rootUser | default "minioautumn" | quote }}
            - name: S3_SECRET_KEY
              value: {{ .Values.global.subcharts.minio.secret_access_key | default .Values.minio.rootPassword | default "minioautumn" | quote }}
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

