{{- $vi := .Values.voiceIngress -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stoatchat.fullname" . }}-voice-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "stoatchat.labels" . | nindent 4 }}
    stoat-app: {{ include "stoatchat.fullname" . }}-voice-ingress
spec:
  type: {{ $vi.service.type }}
  ports:
    - name: http
      targetPort: http
      protocol: TCP
      port: 8500
  selector:
    {{- include "stoatchat.selectorLabels" . | nindent 4 }}
    stoat-app: {{ include "stoatchat.fullname" . }}-voice-ingress
