apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "stoatchat.fullname" . }}-january"
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "stoatchat.labels" . | nindent 4 }}
    stoat-app: {{ include "stoatchat.fullname" . }}-january
spec:
  replicas: {{ .Values.january.replicaCount }}
  selector:
    matchLabels:
      {{- include "stoatchat.selectorLabels" . | nindent 6 }}
      stoat-app: {{ include "stoatchat.fullname" . }}-january
  template:
    metadata:
      {{- with .Values.january.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        stoat-app: {{ include "stoatchat.fullname" . }}-january
        {{- include "stoatchat.labels" . | nindent 8 }}
        {{- with .Values.january.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: january
          image: "{{ .Values.january.image.repository }}:{{ .Values.january.image.tag }}"
          imagePullPolicy: {{ .Values.january.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 14705
              protocol: TCP
          livenessProbe:
            {{- if .Values.january.livenessProbe }}
            {{- toYaml .Values.january.livenessProbe | nindent 12 }}
            {{- else }}
            tcpSocket:
              port: {{ .Values.global.january.port }}
            initialDelaySeconds: 15
            periodSeconds: 30
            {{- end }}
          readinessProbe:
            {{- if .Values.january.readinessProbe }}
            {{- toYaml .Values.january.readinessProbe | nindent 12 }}
            {{- else }}
            tcpSocket:
              port: {{ .Values.global.january.port }}
            initialDelaySeconds: 15
            periodSeconds: 30
            {{- end }}
          {{- with .Values.january.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              subPath: Revolt.toml
              mountPath: {{ .Values.january.configMountPath }}
            {{- with .Values.january.extra_volumeMounts }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "stoatchat.fullname" . }}-config
        {{- with .Values.january.extra_volumes }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.january.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.january.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.january.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
