apiVersion: v1
kind: Service
metadata:
  name: {{ include "stoatchat.fullname" . }}-january
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "stoatchat.labels" . | nindent 4 }}
    stoat-app: {{ include "stoatchat.fullname" . }}-january
spec:
  type: {{ .Values.january.service.type }}
  ports:
    - name: http
      targetPort: http
      protocol: TCP
      port: {{ .Values.global.january.port }}
  selector:
    {{- include "stoatchat.selectorLabels" . | nindent 4 }}
    stoat-app: {{ include "stoatchat.fullname" . }}-january
