apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "stoatchat.fullname" . }}-web"
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "stoatchat.labels" . | nindent 4 }}
    stoat-app: {{ include "stoatchat.fullname" . }}-web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "stoatchat.selectorLabels" . | nindent 6 }}
      stoat-app: {{ include "stoatchat.fullname" . }}-web
  template:
    metadata:
      {{- with .Values.web.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        stoat-app: {{ include "stoatchat.fullname" . }}-web
        {{- include "stoatchat.labels" . | nindent 8 }}
        {{- with .Values.web.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          env:
            - name: VITE_API_URL
              value: "https://{{ .Values.global.domain }}/api"
            - name: VITE_WS_URL
              value: "wss://{{ .Values.global.domain }}/ws"
            - name: VITE_MEDIA_URL
              value: "https://{{ .Values.global.domain }}/autumn"
            - name: VITE_PROXY_URL
              value: "https://{{ .Values.global.domain }}/january"
            - name: REVOLT_PUBLIC_URL
              value: "https://{{ .Values.global.domain }}"
            {{- with .Values.global.config.security.captcha.hcaptcha_sitekey }}
            - name: VITE_HCAPTCHA_SITEKEY
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.web.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.global.web.port }}
              protocol: TCP
          livenessProbe:
            {{- if .Values.web.livenessProbe }}
            {{- toYaml .Values.web.livenessProbe | nindent 12 }}
            {{- else }}
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            {{- end }}
          readinessProbe:
            {{- if .Values.web.readinessProbe }}
            {{- toYaml .Values.web.readinessProbe | nindent 12 }}
            {{- else }}
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            {{- end }}
          {{- with .Values.web.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
            {{- with .Values.web.extra_volumeMounts }}
          volumeMounts:
            {{ toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "stoatchat.fullname" . }}-config
            items:
              - key: Revolt.toml
                path: Revolt.toml
        {{- with .Values.web.extra_volumes }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
