apiVersion: v1
kind: Service
metadata:
  name: {{ include "stoatchat.fullname" . }}-web
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "stoatchat.labels" . | nindent 4 }}
    stoat-app: {{ include "stoatchat.fullname" . }}-web
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - name: http
      targetPort: http
      protocol: TCP
      port: {{ .Values.global.web.port }}
  selector:
    {{- include "stoatchat.selectorLabels" . | nindent 4 }}
    stoat-app: {{ include "stoatchat.fullname" . }}-web
