apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "stoatchat.fullname" . }}-autumn"
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "stoatchat.labels" . | nindent 4 }}
    stoat-app: {{ include "stoatchat.fullname" . }}-autumn
spec:
  replicas: {{ .Values.autumn.replicaCount }}
  selector:
    matchLabels:
      {{- include "stoatchat.selectorLabels" . | nindent 6 }}
      stoat-app: {{ include "stoatchat.fullname" . }}-autumn
  template:
    metadata:
      {{- with .Values.autumn.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        stoat-app: {{ include "stoatchat.fullname" . }}-autumn
        {{- include "stoatchat.labels" . | nindent 8 }}
        {{- with .Values.autumn.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: autumn
          image: "{{ .Values.autumn.image.repository }}:{{ .Values.autumn.image.tag }}"
          imagePullPolicy: {{ .Values.autumn.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 14704
              protocol: TCP
          livenessProbe:
            {{- if .Values.autumn.livenessProbe }}
            {{- toYaml .Values.autumn.livenessProbe | nindent 12 }}
            {{- else }}
            tcpSocket:
              port: {{ .Values.global.autumn.port }}
            initialDelaySeconds: 15
            periodSeconds: 30
            {{- end }}
          readinessProbe:
            {{- if .Values.autumn.readinessProbe }}
            {{- toYaml .Values.autumn.readinessProbe | nindent 12 }}
            {{- else }}
            tcpSocket:
              port: {{ .Values.global.autumn.port }}
            initialDelaySeconds: 15
            periodSeconds: 30
            {{- end }}
          {{- with .Values.autumn.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              subPath: Revolt.toml
              mountPath: {{ .Values.autumn.configMountPath }}
            {{- with .Values.autumn.extra_volumeMounts }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "stoatchat.fullname" . }}-config
        {{- with .Values.autumn.extra_volumes }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.autumn.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.autumn.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.autumn.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
