apiVersion: v1
kind: Service
metadata:
  name: {{ include "stoatchat.fullname" . }}-autumn
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "stoatchat.labels" . | nindent 4 }}
    stoat-app: {{ include "stoatchat.fullname" . }}-autumn
spec:
  type: {{ .Values.autumn.service.type }}
  ports:
    - name: http
      targetPort: http
      protocol: TCP
      port: {{ .Values.global.autumn.port }}
  selector:
    {{- include "stoatchat.selectorLabels" . | nindent 4 }}
    stoat-app: {{ include "stoatchat.fullname" . }}-autumn
