{{- if .Values.gifbox.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "stoatchat.fullname" . }}-gifbox"
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "stoatchat.labels" . | nindent 4 }}
    stoat-app: {{ include "stoatchat.fullname" . }}-gifbox
spec:
  replicas: {{ .Values.gifbox.replicaCount }}
  selector:
    matchLabels:
      {{- include "stoatchat.selectorLabels" . | nindent 6 }}
      stoat-app: {{ include "stoatchat.fullname" . }}-gifbox
  template:
    metadata:
      {{- with .Values.gifbox.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        stoat-app: {{ include "stoatchat.fullname" . }}-gifbox
        {{- include "stoatchat.labels" . | nindent 8 }}
        {{- with .Values.gifbox.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: gifbox
          image: "{{ .Values.gifbox.image.repository }}:{{ .Values.gifbox.image.tag }}"
          imagePullPolicy: {{ .Values.gifbox.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 14706
              protocol: TCP
          livenessProbe:
            {{- if .Values.gifbox.livenessProbe }}
            {{- toYaml .Values.gifbox.livenessProbe | nindent 12 }}
            {{- else }}
            tcpSocket:
              port: {{ .Values.global.gifbox.port }}
            initialDelaySeconds: 15
            periodSeconds: 30
            {{- end }}
          readinessProbe:
            {{- if .Values.gifbox.readinessProbe }}
            {{- toYaml .Values.gifbox.readinessProbe | nindent 12 }}
            {{- else }}
            tcpSocket:
              port: {{ .Values.global.gifbox.port }}
            initialDelaySeconds: 15
            periodSeconds: 30
            {{- end }}
          {{- with .Values.gifbox.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              subPath: Revolt.toml
              mountPath: {{ .Values.gifbox.configMountPath }}
            {{- with .Values.gifbox.extra_volumeMounts }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "stoatchat.fullname" . }}-config
        {{- with .Values.gifbox.extra_volumes }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.gifbox.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gifbox.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gifbox.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
