{{- $vi := .Values.voiceIngress -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "stoatchat.fullname" . }}-voice-ingress"
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "stoatchat.labels" . | nindent 4 }}
    stoat-app: {{ include "stoatchat.fullname" . }}-voice-ingress
spec:
  replicas: {{ $vi.replicaCount }}
  selector:
    matchLabels:
      {{- include "stoatchat.selectorLabels" . | nindent 6 }}
      stoat-app: {{ include "stoatchat.fullname" . }}-voice-ingress
  template:
    metadata:
      {{- with $vi.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        stoat-app: {{ include "stoatchat.fullname" . }}-voice-ingress
        {{- include "stoatchat.labels" . | nindent 8 }}
        {{- with $vi.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: voice-ingress
          image: "{{ $vi.image.repository }}:{{ $vi.image.tag }}"
          imagePullPolicy: {{ $vi.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8500
              protocol: TCP
          {{- if $vi.livenessProbe }}
          livenessProbe:
            {{- toYaml $vi.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if $vi.readinessProbe }}
          readinessProbe:
            {{- toYaml $vi.readinessProbe | nindent 12 }}
          {{- end }}
          {{- with $vi.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              subPath: Revolt.toml
              mountPath: {{ $vi.configMountPath }}
            {{- with $vi.extra_volumeMounts }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "stoatchat.fullname" . }}-config
            items:
              - key: Revolt.toml
                path: Revolt.toml
        {{- with $vi.extra_volumes }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      {{- with $vi.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $vi.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $vi.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
