apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "stoatchat.fullname" . }}-bonfire"
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "stoatchat.labels" . | nindent 4 }}
    stoat-app: {{ include "stoatchat.fullname" . }}-bonfire
spec:
  replicas: {{ .Values.bonfire.replicaCount }}
  selector:
    matchLabels:
      {{- include "stoatchat.selectorLabels" . | nindent 6 }}
      stoat-app: {{ include "stoatchat.fullname" . }}-bonfire
  template:
    metadata:
      {{- with .Values.bonfire.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        stoat-app: {{ include "stoatchat.fullname" . }}-bonfire
        {{- include "stoatchat.labels" . | nindent 8 }}
        {{- with .Values.bonfire.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: bonfire
          image: "{{ .Values.bonfire.image.repository }}:{{ .Values.bonfire.image.tag }}"
          imagePullPolicy: {{ .Values.bonfire.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 14703
              protocol: TCP
          env:
            - name: RUST_BACKTRACE
              value: 'full'
          livenessProbe:
            {{- if .Values.bonfire.livenessProbe }}
            {{- toYaml .Values.bonfire.livenessProbe | nindent 12 }}
            {{- else }}
            tcpSocket:
              port: {{ .Values.global.bonfire.port }}
            initialDelaySeconds: 15
            periodSeconds: 30
            {{- end }}
          readinessProbe:
            {{- if .Values.bonfire.readinessProbe }}
            {{- toYaml .Values.bonfire.readinessProbe | nindent 12 }}
            {{- else }}
            tcpSocket:
              port: {{ .Values.global.bonfire.port }}
            initialDelaySeconds: 15
            periodSeconds: 30
            {{- end }}
          {{- with .Values.bonfire.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              subPath: Revolt.toml
              mountPath: {{ .Values.bonfire.configMountPath }}
            {{- with .Values.bonfire.extra_volumeMounts }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "stoatchat.fullname" . }}-config
            items:
              - key: Revolt.toml
                path: Revolt.toml
        {{- with .Values.bonfire.extra_volumes }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.bonfire.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bonfire.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bonfire.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
